### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by varqox** [Peroniada/ews-tdst-wrapper#1]
Znalazłem parę błędów:
- Jak klikasz "Nie mogę tego zrobić" to czasem nie przechodzi do następnego zadania, jak się to poklika jakieś 20 razy jak np. masz 3 zdania do zrobienia, to te zadania się duplikują w Todoist.
- Jak odświeżysz stronę, to znikają zadania które się dziś zrobiło.
- Dodawanie zadań: wygląda OK, ale jak się doda parę zadań i stronę odświeży, to lądują one na końcu listy zadań do zrobienia (w Todoist to można łatwo sprawdzić).

**Comment by Peroniada** [comment]
Cześć, dzięki za informacje, co do błędów, to co do pierwszego mam już świadomość, drugie jest by design, lecz w sumie można je zapisywać, trzeciego nie jestem w stanie na razie zreprodukować. Zajmę się tym w tygodniu :)

**Comment by Peroniada** [comment]
wszystko powinno być już ok

**Comment by varqox** [comment]
Wyświetlanie zrobionych zadań działa. Jednak dalej są pewne problemy:
- dodawanie zadań przestało działać
- klikanie "Nie mogę tego zrobić" dalej może powodować duplikacje zadań:
Way to reproduce:
1. Wchodzę no todoista i dodaję kilka zadań np.:
![image](https://user-images.githubusercontent.com/4380808/42133485-50c3a4a0-7d2b-11e8-874d-6eb0bdb0be93.png)
2. wchodzę na EWS Todoist Wrapper i w konsolce chroma wklejam linijkę:
```js
for (var i = 1; i <= 50; i++) setTimeout(function(){document.querySelector('div > button + button').click();}, Math.floor(i / 10) * 2000 + 5000 / ((i / 2) % 10 + 1));
```
![image](https://user-images.githubusercontent.com/4380808/42133506-d3512da2-7d2b-11e8-8b25-b9caa4da3b61.png)
Klikam enter (odpalam komendę - tę linijkę), czekam jakieś 20 sekund i dostaję coś takiego:
![image](https://user-images.githubusercontent.com/4380808/42133521-0e05f8d8-7d2c-11e8-92a1-4d08db441ee8.png)
a na todoist coś takiego:
![image](https://user-images.githubusercontent.com/4380808/42133529-2a885848-7d2c-11e8-9d64-fc4b66d1f2b5.png)
Powyższa komenda symuluje szybkie klikanie w przycisk "Nie mogę tego zrobić". Jeżeli nie dostaniesz podobnego efektu jak powyżej to spróbuj kilka razy powtórzyć powyższą procedurę.

Mam nadzieję, że pomogłem. Nie licząc tych dwóch rzeczy to naprawdę świetny wrapper.
